const projectsData = [
  {
    id: 1,
    title: "Roamella | Property Rental Platform",
    description:
      "A rental platform to browse and manage listings with secure login, image uploads, reviews, category filters, and a responsive UI.",
    category: "fullstack",
    image: "/roamella.png",
    tech: [
      "EJS",
      "Node.js",
      "Bootstrap",
      "CSS",
      "JavaScript",
      "Express.js",
      "Passport.js",
    ],
    live: " https://roamella.onrender.com/listings",
    github: "#",
    date: "Novemeber 2025",
    keyFeatures: [
      "CRUD functionality for property listings",
      "RESTful APIs for listings, users, and reviews following MVC architecture",
      "Secure authentication and role-based authorization using Passport.js",
      "Image upload via Multer and optimized storage with Cloudinary",
      "Review and rating system with ownership validation and protected routes",
      "Category-based filtering and dynamic listing views using EJS",
      "Responsive UI built with Bootstrap, ensuring cross-device compatibility",
      "Server-side validation, flash messages, and form validations",
    ],
    futureImprovements: [
      "Booking functionality",
      "Wishlist feature ",
      "Admin dashboard ",
      "Host dashboard ",
      "Admin dashboard",
      "Chat between host & user",
    ],
  },
  {
    id: 2,
    title: "Weather App",
    description:
      "A responsive weather app that fetches real-time data from a public API.",
    category: "frontend",
    image: "/Weather.png",
    tech: ["React.js", "CSS", "Material UI", "API Integration"],
    live: "https://weatherapp-vw8v.onrender.com",
    github: "https://github.com/shrawanimedankar/WeatherApp",
    date: "January 2026",
    keyFeatures: [
      "Developed a responsive React weather app using Material UI that fetches real-time data from a public API.",
      "Implemented city search, detailed weather info (temperature, humidity, wind, sunrise/sunset, min/max) and dynamic backgrounds with smooth transitions",
      "Used React Hooks (useState, useEffect) and deployed on Render with GitHub.",
    ],
    futureImprovements: [
      "7-day weather forecast.",
      "Animations for rain, snow, and thunderstorms.",
    ],
  },
  {
    id: 3,
    title: "Portfolio",
    description: "",
    category: "frontend",
    image: "/portfolio.png",
    tech: ["React.js", "CSS", "", ""],
    live: "https://weatherapp-vw8v.onrender.com",
    github: "https://github.com/shrawanimedankar/WeatherApp",
    date: "November 2025",
    keyFeatures: ["", "", ""],
    futureImprovements: ["", ""],
  },
  {
    id: 4,
    title: "Random Joke Generator",
    description:
      "An app that fetches and displays random jokes. Users can choose categories and get new jokes instantly.",
    category: "frontend",
    image: "/joke.png",
    tech: ["React.js", "JavaScript", "CSS"],
    live: "https://random-joke-generator-vlnc.onrender.com/",
    github: "https://github.com/shrawanimedankar/Random-Joke-Generator-",
    date: "December 2026",
    keyFeatures: [
      "Fetches jokes from an external API",
      "Category selection (Random, General, Programming, Knock-Knock)",
      "Generate new joke on button click",
      "Loading indicator while fetching data",
      "Clean card-based UI",
      "Fully responsive design",
    ],
    futureImprovements: [
      "Copy joke to clipboard",
      "Favorite jokes list",
      "Search jokes by keyword",
      "Share joke on social media",
      "Display joke rating (like / dislike)",
    ],
  },
  {
    id: 5,
    title: "Simon Game",
    description:
      "A fun game that tests memory and reflexes by repeating flashing color sequences.",
    category: "frontend",
    image: "/simon.png",
    tech: ["HTML", "JavaScript", "CSS"],
    live: "https://simon-says-game-7pno.onrender.com",
    github: "https://github.com/shrawanimedankar/Simon-Says-Game",
    date: "October 2025",
    keyFeatures: [
      "Four colored buttons: Red, Blue, Green, and Yellow",
      "Random sequence generation that grows every level",
      "Flash animation and sound effects for feedback",
      "High Score tracking using localStorage",
      "Mobile-friendly and responsive design",
      "Game Over effect when a wrong button is clicked",
    ],
    futureImprovements: [
      "Add difficulty levels (Easy, Medium, Hard)",
      "Include keyboard controls for better accessibility",
      "Make the game progressively faster as levels increase",
    ],
  },
  {
    id: 6,
    title: "Lottery-Game",
    description:
      "Game where users can generate random tickets and celebrate with confetti when they win.",
    category: "frontend",
    image: "/lottery.png",
    tech: ["React.js", "JavaScript", "CSS"],
    live: "https://lottery-game-olfn.onrender.com",
    github: "https://github.com/shrawanimedankar/Lottery-Game",
    date: "December 2026",
    keyFeatures: [
      "Generates random lottery numbers",
      "Check for winning tickets (all numbers match).",
      "Confetti animation on win.",
      "Fully responsive and visually appealing.",
    ],
    futureImprovements: ["", "", "", ""],
  },
  {
    id: 7,
    title: "Quick Notes",
    description: "sequences",
    category: "frontend",
    image: "/quickNotes.png",
    tech: ["React", "Tailwind CSS", "JavaScript"],
    live: "https://quick-notes-q1fj.onrender.com",
    github: "https://github.com/shrawanimedankar/quick-notes",
    date: "October 2025",
    keyFeatures: [
      "Create, edit, delete, and search notes.",
      "Dark Mode Toggle",
      "Data saved in localStorage",
      "Clear All Notes  ",
      "Fully Responsive Design",
    ],
    futureImprovements: [
      "Add categories or tags",
      "Add note pin feature",
      "Add backend database (MongoDB)",
      "Secure authentication and user accounts.",
      "Cloud storage for accessing notes from any device.",
    ],
  },
  {
    id: 8,
    title: "To-Do-List",
    description:
      "It allows users to add, delete, and mark todos as done. Designed with a clean UI using CSS Flexbox and supports mobile responsiveness.",
    category: "frontend",
    image: "/todoList.png",
    tech: ["React.js", "JavaScript", "CSS"],
    live: "",
    github: "",
    date: "October 2025",
    keyFeatures: [
      "Add new todos",
      "Mark individual todos as done/undone",
      "Mark all todos as done",
      "Delete individual todos",
      "Responsive design for desktop and mobile",
      "Unique IDs for todos using uuid",
    ],
    futureImprovements: [
      "Add Local Storage support to persist tasks after page refresh",
      "Implement Edit Todo functionality",
      "Add Due Date & Time picker for tasks",
      "Create Filter options (All, Completed, Pending)",
      "Add Search functionality",
      "Implement Dark / Light mode toggle",
      "Add User Authentication (Login/Signup)",
    ],
  },
];

export default projectsData;
